# Docker Compose for Motor Scout Bot - Development Setup

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motor-scout-bot-dev
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - DEVELOPMENT=${DEVELOPMENT}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      # Mount source code for development (hot reload)
      - ./src:/app/src
      - ./.env:/app/.env
    networks:
      - motor-scout-network

  db:
    image: postgres:15-alpine
    container_name: motor-scout-db-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=motor_scout_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d motor_scout_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - motor-scout-network

  # Optional: PgAdmin for database management (remove if not needed)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: motor-scout-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@motorscout.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - motor-scout-network
    profiles:
      - admin

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  motor-scout-network:
    driver: bridge
