# Render deployment configuration
services:
  - type: web
    name: car-scout-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PRODUCTION
        value: true
    autoDeploy: true
